# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 小亮的碎碎念
email: hel13140302@126.com
description: > # this means to ignore newlines until "baseurl:"
  工作学习中的心得记录。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.hxl2lgy.top" # the base hostname & protocol for your site
twitter_username: ShawnHe1
github_username: Snoopyjoy

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-135024177-1
baidu_analytics: e1a602785c1e8ae7827b228c6a55c360
disqus_shortname: gitblog-6
keywords: node.js,redis,全栈开发,技术博客
gitman:
  client_id: 1648bd782d5ebaf37b40
  client_secret: dbf2d19c7f4d59ef2b8142895fb330f5c2600382
  client_repo: blog

# used this for post_excerpt at index_page
excerpt_separator: 一个node.js全栈开发工程师的心路历程
