# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 小亮的博客
email: hel13140302@126.com
description: > # this means to ignore newlines until "baseurl:"
  工作学习中的心得记录。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.hxl2lgy.top" # the base hostname & protocol for your site
twitter_username: ShawnHe1
github_username: Snoopyjoy
icp: 沪ICP备18001052号-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-135024177-1
baidu_analytics: 38eb0a2f579657f5786a11f5e7300c50
disqus_shortname: gitblog-6
keywords: 小亮,小亮的博客,node.js开发,全栈开发工程师,技术博客
gitman:
  client_id: 1648bd782d5ebaf37b40
  client_secret: dbf2d19c7f4d59ef2b8142895fb330f5c2600382
  client_repo: blog
mob: 2a2eda40eebf8
# used this for post_excerpt at index_page
excerpt_separator: 一个node.js全栈开发工程师的心路历程
